# Generated by Django 4.2 on 2023-04-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='turno',
            name='comentario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='turno',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='turno',
            name='vehiculo',
            field=models.CharField(max_length=50),
        ),
    ]
