# Generated by Django 4.2 on 2023-04-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_autos', '0002_alter_turno_apellido_alter_turno_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
